obj-y += dsim_panel.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE)	+= mdnie_lite.o

obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA0)	+= s6e3fa0_mipi_lcd.o s6e3fa0_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA3)	+= s6e3fa3_mipi_lcd.o s6e3fa3_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA7)	+= s6e3fa7_mipi_lcd.o s6e3fa7_lcd_ctrl.o

obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA7_A5Y18)	+= s6e3fa7_a7y18_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA7_A7Y18)	+= s6e3fa7_a7y18_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_EXYNOS_DECON_LCD_TD4100_J3TOPE)	+= td4100_j3tope_lcd_ctrl.o td4100_j3tope_old_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6D7AT0B_J7TOPE)	+= s6d7at0b_j7tope_lcd_ctrl.o td4100_j7tope_lcd_ctrl.o
