# drivers/staging/sec_abc/Makefile
#
# Copyright (c) 2010-2011 Samsung Electronics Co., Ltd.
#		http://www.samsung.com/
#
# Licensed under GPLv2

# Samsung sec ABC Feature
obj-$(CONFIG_SEC_ABC)		+= sec_abc.o
