dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

dtb-$(CONFIG_SOC_EXYNOS8890) += exynos8890-maestro.dtb
dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-smdk8895.dtb
dtb-$(CONFIG_SOC_EMULATOR7872) += exynos7872-emulator7872.dtb
dtb-$(CONFIG_SOC_EXYNOS7872) += exynos7872-smdk7872.dtb
dtb-$(CONFIG_SOC_EXYNOS7872) += exynos7872-maestro7872.dtb
dtb-$(CONFIG_SOC_EXYNOS7885) += exynos7885-smdk7885.dtb
dtb-$(CONFIG_SOC_EXYNOS7885) += exynos7885-universal7885.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
