dtb-y += exynos7885-jackpotlte_eur_open_00.dtb
dtb-y += exynos7885-jackpotlte_eur_open_01.dtb
dtb-y += exynos7885-jackpotlte_eur_open_02.dtb
dtb-y += exynos7885-jackpotlte_eur_open_03.dtb
dtb-y += exynos7885-jackpotlte_eur_open_04.dtb
dtb-y += exynos7885-jackpotlte_eur_open_05.dtb
dtb-y += exynos7885-jackpotlte_eur_open_06.dtb
dtb-y += exynos7885-jackpotlte_eur_open_07.dtb

dtb-y += exynos7885-jackpot2lte_eur_open_00.dtb
dtb-y += exynos7885-jackpot2lte_eur_open_01.dtb
dtb-y += exynos7885-jackpot2lte_eur_open_02.dtb
dtb-y += exynos7885-jackpot2lte_eur_open_03.dtb
dtb-y += exynos7885-jackpot2lte_eur_open_04.dtb
dtb-y += exynos7885-jackpot2lte_eur_open_05.dtb
dtb-y += exynos7885-jackpot2lte_eur_open_06.dtb
dtb-y += exynos7885-jackpot2lte_eur_open_07.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
