dtb-$(CONFIG_MACH_EXYNOS7884_A6ELTE_USA) := \
	exynos7884-a6elte_usa_00.dtb \
	exynos7884-a6elte_usa_03.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A7Y18LTE_EUR_OPEN) := \
	exynos7885-a7y18lte_eur_open_00.dtb \
	exynos7885-a7y18lte_eur_open_01.dtb \
	exynos7885-a7y18lte_eur_open_03.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOT2LTE_EUR_OPEN) := \
	exynos7885-jackpot2lte_eur_open_00.dtb \
	exynos7885-jackpot2lte_eur_open_01.dtb \
	exynos7885-jackpot2lte_eur_open_02.dtb \
	exynos7885-jackpot2lte_eur_open_03.dtb \
	exynos7885-jackpot2lte_eur_open_04.dtb \
	exynos7885-jackpot2lte_eur_open_05.dtb \
	exynos7885-jackpot2lte_eur_open_06.dtb \
	exynos7885-jackpot2lte_eur_open_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_CAN_OPEN) := \
	exynos7885-jackpotlte_can_open_00.dtb \
	exynos7885-jackpotlte_can_open_01.dtb \
	exynos7885-jackpotlte_can_open_02.dtb \
	exynos7885-jackpotlte_can_open_03.dtb \
	exynos7885-jackpotlte_can_open_04.dtb \
	exynos7885-jackpotlte_can_open_05.dtb \
	exynos7885-jackpotlte_can_open_06.dtb \
	exynos7885-jackpotlte_can_open_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_EUR_OPEN) := \
	exynos7885-jackpotlte_eur_open_00.dtb \
	exynos7885-jackpotlte_eur_open_01.dtb \
	exynos7885-jackpotlte_eur_open_02.dtb \
	exynos7885-jackpotlte_eur_open_03.dtb \
	exynos7885-jackpotlte_eur_open_04.dtb \
	exynos7885-jackpotlte_eur_open_05.dtb \
	exynos7885-jackpotlte_eur_open_06.dtb \
	exynos7885-jackpotlte_eur_open_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_JPN_DCM) := \
	exynos7885-jackpotlte_jpn_dcm_00.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_KOR) := \
	exynos7885-jackpotlte_kor_00.dtb \
	exynos7885-jackpotlte_kor_01.dtb \
	exynos7885-jackpotlte_kor_02.dtb \
	exynos7885-jackpotlte_kor_03.dtb \
	exynos7885-jackpotlte_kor_04.dtb \
	exynos7885-jackpotlte_kor_05.dtb \
	exynos7885-jackpotlte_kor_06.dtb \
	exynos7885-jackpotlte_kor_07.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
